version: "3.8"

services:
  validator1:
    image: hyperledger/besu:22.4.2
    container_name: validator1
    networks:
      besu-network:
        ipv4_address: 172.28.0.2
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/config/genesis.json
      --network-id=1337
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --host-allowlist=*
      --sync-mode=FULL
      --node-private-key-file=/opt/besu/data/key
      --rpc-http-api=ETH,NET,WEB3,ADMIN
      --p2p-host=172.28.0.2
      --p2p-port=30303
    volumes:
      - ./networkFiles/genesis.json:/opt/besu/config/genesis.json
      - ./networkFiles/0x3f3c2645815f59857b0f7507ccb001769f65cc54:/opt/besu/data
    ports:
      - "8541:8545" # RPC HTTP
      - "30303:30303" # P2P

  validator2:
    image: hyperledger/besu:22.4.2
    container_name: validator2
    networks:
      besu-network:
        ipv4_address: 172.28.0.3
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/config/genesis.json
      --network-id=1337
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --host-allowlist=*
      --sync-mode=FULL
      --node-private-key-file=/opt/besu/data/key
      --rpc-http-api=ETH,NET,WEB3,ADMIN
      --p2p-host=172.28.0.3
      --p2p-port=30303
    volumes:
      - ./networkFiles/genesis.json:/opt/besu/config/genesis.json
      - ./networkFiles/0x4eb2d1160dd181d354c4065f128c2218feb19fa2:/opt/besu/data
    ports:
      - "8542:8545"
      - "30304:30303"

  validator3:
    image: hyperledger/besu:22.4.2
    container_name: validator3
    networks:
      besu-network:
        ipv4_address: 172.28.0.4
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/config/genesis.json
      --network-id=1337
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --host-allowlist=*
      --sync-mode=FULL
      --node-private-key-file=/opt/besu/data/key
      --rpc-http-api=ETH,NET,WEB3,ADMIN
      --p2p-host=172.28.0.4
      --p2p-port=30303
    volumes:
      - ./networkFiles/genesis.json:/opt/besu/config/genesis.json
      - ./networkFiles/0x87401b92fce9cf00015e4cf38d6db05f6003088c:/opt/besu/data
    ports:
      - "8543:8545"
      - "30305:30303"

  validator4:
    image: hyperledger/besu:22.4.2
    container_name: validator4
    networks:
      besu-network:
        ipv4_address: 172.28.0.5
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/config/genesis.json
      --network-id=1337
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --host-allowlist=*
      --sync-mode=FULL
      --node-private-key-file=/opt/besu/data/key
      --rpc-http-api=ETH,NET,WEB3,ADMIN
      --p2p-host=172.28.0.5
      --p2p-port=30303
    volumes:
      - ./networkFiles/genesis.json:/opt/besu/config/genesis.json
      - ./networkFiles/0xdd47bca95d975b0f4e3a8f577c37cf5c872d0d39:/opt/besu/data
    ports:
      - "8544:8545"
      - "30306:30303"

  ##############################
  #      ELASTICSEARCH        #
  ##############################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    networks:
      - besu-network
    ports:
      - "9200:9200"

  ##############################
  #         LOGSTASH          #
  ##############################
  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: logstash
    depends_on:
      - elasticsearch
    networks:
      - besu-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044" # Beats input
      - "9600:9600" # Monitoring API (optional)

  ##############################
  #          KIBANA           #
  ##############################
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - besu-network
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  ##############################
  #         FILEBEAT          #
  ##############################
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    depends_on:
      - logstash
    networks:
      - besu-network
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount Docker socket
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
