filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock" # Ensure Docker socket is accessible
          match_source: true

# refine search to only include logs from the container named "validator"
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.name: "validator"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/*/*.log
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"
                    match_source: true

output.logstash:
  hosts: ["logstash:5044"]
